Task 11 first reveiw
Maksym-Lizohub/magento pull request #10
Opened 2022-12-20 13:34 UTC by Maksym-Lizohub

2022-12-22 10:18 UTC, y-mantuliak requested changes

2022-12-22 10:18 UTC, y-mantuliak commented on app/design/frontend/Elogic/maksym/Magento_Catalog/layout/catalog_product_view.xml
> +    <update handle="page_calendar"/>
```
<head>
      <css src="mage/gallery/gallery.css"/>
</head>
<update handle="catalog_product_opengraph" />
<update handle="page_calendar"/>
```

You don't need these instructions as you already have them in vendor module

2022-12-22 12:54 UTC, Maksym-Lizohub commented on app/design/frontend/Elogic/maksym/Magento_Catalog/layout/catalog_product_view.xml
> +    <update handle="page_calendar"/>
Noted / done

2022-12-29 11:28 UTC, y-mantuliak approved these changes

2022-12-29 12:43 UTC, merged