Task 14  first reveiw
Maksym-Lizohub/magento pull request #12
Opened 2022-12-26 10:00 UTC by Maksym-Lizohub

2022-12-29 11:40 UTC, y-mantuliak requested changes

2022-12-29 11:40 UTC, y-mantuliak commented on app/code/Maksym/GalleryPage/etc/module.xml
> +    <module name="Maksym_GalleryPage" setup_version="1.0.1"></module>
You don't need to add `setup_version`

2022-12-29 12:40 UTC, Maksym-Lizohub commented on app/code/Maksym/GalleryPage/etc/module.xml
> +    <module name="Maksym_GalleryPage" setup_version="1.0.1"></module>
Done / noted with thanks.

2023-01-09 11:29 UTC, y-mantuliak approved these changes

2023-01-09 12:27 UTC, merged