task-3 1st review
Maksym-Lizohub/magento pull request #2
Opened 2022-11-17 13:55 UTC by Maksym-Lizohub

2022-11-21 10:56 UTC, y-mantuliak requested changes
1. Use lib from the ui library likw:
- .lib-font-size()
- .lib-vendor-prefix-display() and other flexbox libs 

2. Use font-size, font-weight, indent and color variables

2022-11-21 10:56 UTC, y-mantuliak commented on app/design/frontend/Elogic/maksym/Magento_Catalog/web/css/source/module/_listings.less
> +                    font-size: @font-size__s;
please use .lib-font-size()

2022-11-21 13:56 UTC, Maksym-Lizohub commented on app/design/frontend/Elogic/maksym/Magento_Catalog/web/css/source/module/_listings.less
> +                    font-size: @font-size__s;
done

2022-11-22 10:21 UTC, y-mantuliak approved these changes

2022-11-24 11:19 UTC, merged